### ISSUE TITLE
Why DUO Log Add-on for Splunk?

### ISSUE THREAD

**Issue by wryanthomas** [bawood/TA-DUOSecurity2FA#6]
Given the availability of Duo Splunk Connector (http://duo.com/docs/splunkapp), it isn't clear from the documentation why this add-on is needed. When should one use DUO Log Add-on for Splunk? Is it intended as a supplement, or a replacement? If supplement, what is the value added?  If replacement, why?  Thanks.

**Comment by bawood** [comment]
This add-on was developed in 2016, simply as a modular input, before DUO had released their app. Our site had a need to index our DUO logs in Splunk and, at the time, DUO seemed to have no knowledge or interest in users being able to "Splunk" their data, therefore I developed this add-on and shared it with the broader Splunk community.  So basically, at this point I would consider it as an alternate to the DUO app, feel free to use theirs instead.  I primarily only work on this add-on in my spare time if there is something needed to keep it functional or significantly improve it.

**Comment by wryanthomas** [comment]
Thanks for the response and thank you for creating this app back then. You might consider giving some hint of this (if not the history, at least that it is now a 3rd-party alternative to DUO's own app) in either the Splunkbase description/detail ... or in the README or other documentation. Just a suggestion. Again, thanks.
